package wdsr.exercise5.dbclient;

/**
 * Created by Piotr on 2017-05-29.
 */
public enum EDatabaseQueries {
    CREATE_TABLE_STUDENT("CREATE TABLE Student(pkey INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY, name VARCHAR(30), sex VARCHAR(6), age INTEGER, level INTEGER);"),
    CREATE_TABLE_FACULTY("CREATE TABLE Faculty(pkey INT NOT NULL PRIMARY KEY,name VARCHAR(50) NOT NULL );"),
    CREATE_TABLE_CLASS("CREATE TABLE Class(pkey INT NOT NULL PRIMARY KEY,name VARCHAR(50) NOT NULL,fkey_faculty INT NOT NULL,FOREIGN KEY (fkey_faculty) REFERENCES Faculty (pkey));"),
    CREATE_TABLE_ENTROLLMENT("CREATE TABLE Enrollment(fkey_student INT NOT NULL, fkey_class INT NOT NULL, FOREIGN KEY (fkey_class) REFERENCES Class (pkey), FOREIGN KEY (fkey_student) REFERENCES Student (pkey));");
    private String query;
    EDatabaseQueries(String query) {
        this.query = query;
        }
    public String getQuery() {
        return query;
    }
}
